config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "events#index"

  resources :events, only: [:index, :new, :create, :show]
  resources :users, only: [:show]
  resources :event_attendees, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :attendee
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :events, foreign_key: :creator_id, class_name: "Event"

  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  self.responder = ApplicationResponder
  respond_to :html

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!

  def create
    event_attendee = EventAttendee.new(attendee_id: current_user.id, attended_event_id: params[:event_id])
    event_attendee.save
    redirect_to root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Event created!"
      redirect_to @event
    else
      flash[:alert].now = "Some error!"
      render :new, status: :unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All upcoming events</h1>

<% @events.each do |event| %>
  <div>
    Event date: <%= event.date %> <br \>
    Event location: <%= event.location %>
  </div>
  <%= link_to 'Show more', event_path(event) %>
  <hr>
<% end %>

app/views/events/new.html.erb
<h2>Create a new event</h2>

<%= form_with model: @event do |form| %>
  <%= form.label :date, "Date:" %>
  <%= form.text_field :date %>

  <br \>

  <%= form.label :location, "Location:" %>
  <%= form.text_field :location %>

  <br \>

  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h2>Event Info</h2>

Date: <%= @event.date %> <br />
Location: <%= @event.location %>

<hr>
<p>Attendees:</p>
<% @event.attendees.each do |attendee| %>
  - <%= attendee.name %><br />
<% end %>

<hr>
<%= button_to 'Enroll', event_attendees_path(event_id: @event.id) %> <br />
TODO: exit (if user enrolled)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h2><%= @user.name %>'s events</h2>

<% @user.events.all.each do |event| %>
  <div>
    Date: <%= event.date %> <br \>
    Location: <%= event.location %>
  </div>
  <hr>
<% end %>

<p>Attended events:</p>
<% @user.attended_events.each do |event| %>
  Date: <%= event.date %> | Location: <%= event.location %><br />
  <hr>
<% end %>